### ISSUE TITLE
Randomly missing handler 

### ISSUE THREAD

**Issue by Diluka** [nestjs/bull#345]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Minimal reproduction of the problem with instructions

https://github.com/Diluka/nest-bull-issue-272

related #272 

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Thanks for sharing the repository. It seems that the race condition occurs in the underlying `bull` package. We'll be migrating to the latest version shortly so hopefully, this will fix this issue.

**Comment by auchEnia** [comment]
I have encountered a similar issue and it took me couple of hours to figure out what was happening. I believe I have encountered the same problem you have @Diluka. 

**Problem**

The problem, in my case, was the fact I was registering more than 1 queue asynchronously. According to the documentation, you need to provide the name of the queue outside of the `useFactory` method as it needs to be known sooner than the `useFactory` method is resolved. This is fine and understandable. But... The name is not correctly picked when a processor is looked up. In fact, this is easy to see using for example `redis-commander` - the job is thrown into the "default" bucket there.

As you have at least 2 queues registered and both asynchronously, they both "compete" for the same "bucket" (default). The processor seems to be picked at random or possibly 1 request going to q1, the second one going to q2, the third one again to q1 and so on to provide some balancing.

The issue is, one of the queues has a handler for the named job, but the other one doesn't. If the request is picked up by the processor without the named handler, we run into this issue. If you had at least one not-named handler in each processor, you wouldn't see this issue, though jobs would most likely continue being lost - just without an "obvious" error.

**Short term solution**

We cannot move the name to the `useFactory` method, but we can have the name both outside and inside. Consider the following example:

```typescript
BullModule.registerQueueAsync(
  {
    name: 'q1',
    useFactory: () => ({
      name: 'q1'
    }),
  },
  {
    name: 'q2',
    useFactory: () => ({
      name: 'q2',
    }),
  },
)
```

This is obviously less than ideal, but this solved my issue.

**Proper fix**

We should make sure the queue name is picked up from outside the `useFactory` method when choosing a job processor for an incoming request in case the queue has been registered using the `registerQueueAsync`.

**Comment by gimyboya** [comment]
i am facing this issue. is there a fix that is going to be implemented?

**Comment by kamilmysliwiec** [comment]
This was fixed as part of this PR https://github.com/nestjs/bull/pull/351
