### ISSUE TITLE
Switch from Bull to Bree due to core issues + leaks + user complexity

### ISSUE THREAD

**Issue by niftylettuce** [nestjs/bull#496]
Hello - I'm just sharing a package I created, which was recently featured on Node Weekly https://nodeweekly.com/issues/347 and has 100% code coverage.  I built it out of frustration with core bugs in Bull, even after having created my own wrapper https://github.com/ladjs/bull.  The author of Bull has blocked me from filing further issues and bugs I have discovered to say the least.

You can read more about it here https://jobscheduler.net/ or directly on GitHub at https://github.com/breejs/bree.

Would love to see Bree used in nestjs!

**Comment by BrunnerLivio** [comment]
I don’t wanna judge this recommendation, since I don’t feel like I have the expertise. Though I want to extend @niftylettuce issue, since important points we should consider in order to make a decision:

From [breejs Readme](https://github.com/breejs/bree#alternatives-that-are-not-production-ready):
> * bull has core issues with [repeatable jobs](https://github.com/OptimalBits/bull/issues/1739), [emptying of jobs](https://github.com/OptimalBits/bull/issues/1792), and [event emitters](https://github.com/OptimalBits/bull/issues/1659)
> * [@ladjs/bull][https://github.com/ladjs/bull] used bull internally, but was unusable due to [bull issues](https://github.com/ladjs/bull/issues/2)

**Comment by niftylettuce** [comment]
Yeah, I was even blocked by the Bull maintainers since I was outspoken about these issues - and I'm guessing they don't want people to switch from Bull to Bree.

**Comment by gaurav-** [comment]
Bree looks very interesting based on a quick read of its documentation.  I'd vote for a separate `nestjs/bree` package so that the community have alternatives based on the specific needs of different projects

**Comment by andreialecu** [comment]
I was just looking into Bree but I don't see how it can be really used with NestJS and TypeScript in particular.

It seems that jobs are supposed to go into separate `.js` files. That's not really idiomatic NestJS as you can't use dependency injection that way, or it would really overcomplicate things.

What Bree does seems to mostly be the same as https://docs.nestjs.com/techniques/task-scheduling

**Comment by gaurav-** [comment]
> It seems that jobs are supposed to go into separate .js files. That's not really idiomatic NestJS as you can't use dependency injection that way, or it would really overcomplicate things.

I guess it could be similar to how TypeORM allows [specifying path glob for its entities](https://docs.nestjs.com/recipes/sql-typeorm#getting-started).
```ts

export const databaseProviders = [
  {
    provide: 'DATABASE_CONNECTION',
    useFactory: async () => await createConnection({
      ...
      entities: [
          __dirname + '/../**/*.entity{.ts,.js}',
      ],
      ...
    }),
  },
];
```

Another example is of the GraphQLModule which [allows configuring path glob](https://docs.nestjs.com/graphql/quick-start#schema-first) for schema files. 
```ts
GraphQLModule.forRoot({
  typePaths: ['./**/*.graphql'],
  ...
}),
```

**Comment by niftylettuce** [comment]
@andreialecu just note that `@nestjs/schedule` uses node-cron which I am now a maintainer of.  I do not recommend using this.  Not only does bree have cron expression validation support, it also has support for seconds format (6 instead of 5 space delimited expressions), and it spawns workers in sandboxed processes.  It is extremely bad practice to have a shared process with multiple jobs running on it at once, especially when developers forget to wrap their promises with try/catch blocks as I've seen time and time again.

**Comment by andreialecu** [comment]
@gaurav- TypeORM entities contain no code other than decorated properties though. So there is no need for dependency injection. Same for `*.graphql` files.

@niftylettuce I agree that Bree solves some problems. But it's not necessarily for everyone. Seems more of a `node-cron` replacement than a full fledged job queue.

I personally prefer to run my job runners in a cluster across multiple docker containers, for high availability. Seems like Bree isn't fit for that out of the box. I don't see any built-in distributed job locking support, or any sort of persistence mechanism (users need to write their own). I feel there's a much steeper learning curve to this approach. 

The main concern is: I'm not sure how you envision Bree to work with TypeScript in general, or even Babel, considering the need for files to be compiled. Other things like https://nx.dev/ complicate this approach even more. And how about [Deno](https://deno.land/)?

As per your description it seems that Bree is more of a `node-cron` replacement, requiring many things to be coded manually. Note that I do like this approach, and I've been considering using it instead of Bull (probably `@nestjs/schedule` though) in my future projects, because I feel I get more efficiency and control that way. 

I'm sure at some point someone will create a `nestjs-bree` package as an alternative to `@nestjs/schedule`. Here's an example for Agenda: https://www.npmjs.com/package/nestjs-agenda

It just feels that Bree is not quite fit yet for the TypeScript world in general, and I think that NestJS is one of the flagship projects of TypeScript, along with Angular.

**Comment by niftylettuce** [comment]
The core problem that many fail to see nor recognize are that there are core bugs in Bull that are still unresolved.  Sometimes you will make repeatable jobs and they don't start.  I'm not the only one that has reproduced this either.  Just look at all the 300+ GitHub issues filed for Bull.  Relying on Redis for a job scheduler is horrible practice, at the very least go back to Agenda for persistent storage.

**Comment by JVMartin** [comment]
"I also am strongly against TypeScript" (@niftylettuce)

Anyone who is strongly against static typing obviously doesn't understand it. Having a type system is the _only_ way to use AST's to statically refactor projects at-scale, otherwise it would take countless hours to perform basic refactors, causing your project to calcify.

**Comment by niftylettuce** [comment]
I wouldn't be so sure of that @JVMartin.  You know what they say about people that make assumptions 😆

**Comment by kamilmysliwiec** [comment]
`@nestjs/bull` is a wrapper package that aims to simplify the integration process of NestJS applications with Bull which is widely used and very popular in the community. However, it doesn't mean that other existing packages for creating & managing Queues/Jobs shouldn't be used. Developers can pick & choose whatever they want for their projects, that's one of the most important goals of Nest.

As for switching from bull to bree - as the name suggests, this package is a wrapper for Bull (`@nestjs/bull`). There are no plans to create an official wrapper for Bree ATM but we encourage anyone in the community to create a wrapper on your own and share with the community if you think that other people may find it valuable.
