### ISSUE TITLE
Dynamic Bull named Queues creation, registration, with concurrency settings and deletion. 

### ISSUE THREAD

**Issue by ahmad-punch** [nestjs/bull#580]
## Is your feature request related to a problem? Please describe.

Hi guys!

I have integrated Nest Js Queues in my project.
And I have them operational in my MVP use case.
Which is to push process intensive tasks in a single queue so they only get processed one by one. (So our server doesn't crashes)

Now to tackle the multi user case.
For which there is no solution.
Because we cannot pause / resume selective jobs (or a batch of jobs), only the complete queue can be paused or processed.

These are the requirements that we need to tackle:
1-Multiple users pausing / resuming their jobs.
2-Creating limits over how many users we support simultaneously. (so a users queue)
3-Creating how many jobs a user can execute simultaneously.

Now since the no of users is decided at runtime we have to create / register and instantize queues at runtime.
This is not possible as per my knowledge not right now.

## Describe the solution you'd like

Two main possible solutions:
1-Create, register, delete queues at runtime to handle mutiple user cases.
2-Give a queue ability to create, pause, resume, stop, modify multiple jobs or a batch of jobs at runtime,

## Teachability, Documentation, Adoption, Migration Strategy

If bull queue creation is integrated in the Nest Js project at runtime.
https://github.com/OptimalBits/bull#queues-performance
Then Users can say:
1- Create a single global queue to handle all the loads that their server can handle. (say they know that their server can only handle 10 concurrent processing intensive jobs at run time) then this will be the limit of this queue.
2-Create a User queue ( where all the user related jobs can be pushed to this queue, here we can control if a user can run multiple jobs in parallel maybe 2,3 etc. using the concurrency parameter of bull queue using this: 

@Process({ name: "CompleteProcessJobs", concurrency: 1 }) //consumers
  async startProcesisng(job: Job<any>): Promise<string> {return "sample"}

3-Create a batch queue which can add batches of jobs in users queue (so users can have multiple batches of jobs and he can pause / stop or resume that certain batch queue that is under processing)

4-These user queues can be created and destroyed at runtime based on the no of users or their batch requests. And we can have inherent pre defined settings stored to decide their limits.
Overview:
The Global queue will hold Users that are being handled in parallel (rest will wait in queue).
The Users Queue ( will handle batch requests and will create / destroy batch queue as per user requirement)
The Batch Queue (is unique to the user and will hold independent jobs / atomic tasks that need to be done. This will allow user to pause/resume selective batch of jobs) 

## What is the motivation / use case for changing the behavior?

This will enable users to scale their applications very easily to handle all sorts of multiple user scenarios or even if multiple user can have multiple processes running in parallel.

**Comment by kamilmysliwiec** [comment]
I'm not sure whether this issue is a feature request or just a Bull related question. This package simply wraps the existing `bull` package and doesn't provide any additional functionalities on top (except for some decorators that are needed to make it easier to integrate this package with NestJS applications). We don't plan to extend this library in any way (at least for now). Regarding some other things you mentioned in the post, if you need to create a queue dynamically instead of using declarative, static style (with decorators), you can just use `bull` directly (without relying on the `@nestjs/bull` wrapper). Wrapper packages are intended to simplify the integration process with some of the common, existing packages, but are not necessarily required, which means that you can always build your custom solution instead (wrap a library on your own).
